[build]
  functions = "netlify/functions"
  command = "npm install && npm run build && echo Building Functions"
[functions]
  external_node_modules = ["express", "mongoose", "dotenv", "serverless"] # Include any other necessary modules
  node_bundler = "esbuild" # Ensure you use esbuild for better performance
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"